apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-echo
spec:
  selector:
    matchLabels:
      app: my-echo
  replicas: 2
  template:
    metadata:
      labels:
        app: my-echo
    spec:
      containers:
      - name: my-echo
        image: 1270346/my-echo:20250807
---
apiVersion: v1
kind: Service
metadata:
  name: my-echo
spec:
  selectori:
    app: my-echo
  ports:
  - port: 1323
    targetPort: 1323
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-nginx-ing
  labels:
    name: my-echo
spec:
  rules:
  - host: web.127.0.0.1.nip.io
    http:
      paths:
      - pathType: Prefix
        path: /hoge
        backend:
          service:
            name: my-nginx-service
            port: 
              number: 80
